react ts project
fenab-bojko/pet_project pull request #1
Opened 2024-02-29 08:47 UTC by fenab-bojko

2024-02-29 09:28 UTC, Antamansid commented
test comment

2024-02-29 09:34 UTC, Antamansid requested changes
Переименуй `exem_project` в `src`.
PS: у тебя там ошибка орфографическая хД.
Переименуй project в `ui`.
Также проинициализируйся в основную папку

```bash
npm i -y
```
И было бы круто если бы ты добавил `README.md` (напиши пока просто что за проект и все - потом добавим разного)

В конечном итоге у тебя должно быть:
src
-ui
-server
README.md
package.json

2024-02-29 09:45 UTC, Antamansid requested changes
Установи [Prettier](https://khalilstemmler.com/blogs/tooling/prettier/) - тебе будет легче работать с кодом и форматировать его.
И в [VSCODE](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode).
Не забудь про [eslint](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) если он еще не стоит и [prettier для eslint](https://marketplace.visualstudio.com/items?itemName=rvest.vs-code-prettier-eslint)

Будут вопросы - пиши

2024-02-29 09:57 UTC, Antamansid requested changes

2024-02-29 09:57 UTC, Antamansid commented on exem_project/project/src/App.tsx
> +  const sendQuestion  = (question: string, language: string, skill: string, answer: string, name: string) => {
Не, чувак, так не делается.
Если ты пишешь метод для компонента, как здесь `sendQuestion` для `Modal` то ты должен реализовывать тип этого поля в интерфейсе пропсов `Modal`. 

Трудно написал.
Короче тебе надо в компоненте `Modal` сделать интерфейс `IModalProps` (первая буква I обозначает, что это интерфейс, была бы Т - означало, что это тип) (ПС разницы как таковой нет - на вкус и цвет, хочешь - юзай типы, смысл тот же, инструменты другие просто)
И тебе надо описать поля пропсов.
В итоге оно должно выглядеть как-то так

```tsx
export interface IModalProps {
 visible: boolean;
 onSendQuestion: (question: string, language: string, skill: string, answer: string, name: string) => void;
}
```

а тут ты уже импортируешь интерйфес и реализовываешь его поля

```tsx
const sendQuestion: IModalProps["onSendQuestion"] = (question, language, skill, answer, name) => {...}
```

Пройдись везде по коду и посоздавай и проставь интерфейсы.

2024-02-29 09:57 UTC, Antamansid commented on exem_project/project/src/App.tsx
> +  const sendQuestion  = (question: string, language: string, skill: string, answer: string, name: string) => {
Если ты не прячешь функцию в `useCallback` она будет создаваться каждый ререндер.
Если она будет создаваться каждый ререндер - она всегда будет новая.
Эта функция является пропсом для компонента `Modal`.
Как ты помнишь - если пропсы у компонента меняются - компонент ререндерится.
Это надо делать осознанно.
Тут в этом нет смысла.
Оберни в `useCallback` и пройдись по коду у себя поправь везде это.

2024-02-29 10:01 UTC, Antamansid requested changes

2024-02-29 10:01 UTC, Antamansid commented on exem_project/project/models/interfase.ts
> +export interface ModalProps {
О, да у тебя они есть!
Распихай их по компонентам.
Идея клевая, но так никто не делает, да и не удобно это так)

2024-02-29 10:09 UTC, Antamansid requested changes
Переименуй `exem_project` в `src`.
PS: у тебя там ошибка орфографическая хД.
Переименуй project в `ui`.
Также проинициализируйся в основную папку

```bash
npm i -y
```
И было бы круто если бы ты добавил `README.md` (напиши пока просто что за проект и все - потом добавим разного)

В конечном итоге у тебя должно быть:
src
-ui
-server
README.md
package.json

2024-03-01 08:37 UTC, Antamansid requested changes

2024-03-01 08:37 UTC, Antamansid commented on package.json
оО а че он пустой?
Ты просто создал файл без инициализации проекта?

2024-03-01 08:37 UTC, Antamansid commented on src/ui/src/App.tsx
> +  const openModal = useCallback(() => setShowModal(true), [])
А че тут не проставил реализацию поля интерфейса `Content` ?
Ты же в `Content` в `onAddQuestion` передаешь этот метод.

2024-03-01 08:37 UTC, Antamansid commented on src/ui/src/index.css
> +* {
Лучше файлы со стилями называть также как файл с компонентом - так ты сразу понимаешь, что эти стили к этому компоненту (сорян за тофтологию) 

Ты, кстати, везде так и делаешь)))

2024-03-01 08:37 UTC, Antamansid commented on src/ui/src/components/QuestionContainer/QuestionsContainer.tsx
> +                            <p className={visible === elem.id ? '' : 'hidden'}>{elem.answer}</p>
Тут ты можешь обойтись ваще без css
Просто
```tsx
{visible === elem.id ? <p></p> : null}
```

2024-03-01 08:37 UTC, Antamansid commented on src/ui/src/components/QuestionContainer/QuestionsContainer.tsx
> +    }
Разделяй строчкой методы и useEffect-ы

Кстати хорошая практика писать коммент над useEffectом - зачем он?

2024-03-01 08:37 UTC, Antamansid commented on src/ui/src/components/Modal/Modal.tsx
> +                    <input name='name' type="text" value={name} onChange={(e)=>setName(e.target.value)} placeholder='Введите имя'/>
У тебя `onChange` много где используется одинаковый.
Сразу видно - не ленивый, копипастил))

Вытащи ее наверх. Оберни в useCallback и будет счастье.

2024-03-01 08:37 UTC, Antamansid commented on src/ui/src/components/Menu/Menu.tsx
> +
Дофига переносов.
Надо сесть захакатонить линтер тебе с преттиром (донастроить).

2024-03-01 08:37 UTC, Antamansid commented on src/ui/src/components/Header/Header.tsx
> +const Header = memo(function Header() {
Красивое.
Сделай также везде.

2024-03-01 08:37 UTC, Antamansid commented on src/ui/src/components/Header/Header.tsx
> +export default Header;
Только не надо `export default`.
Просто `export`.
Ты можешь заэкспортить типы.
Потом запутаешься - че импортирую по дефолту.
А так нет дефолта - нет проблем.

2024-03-01 08:37 UTC, Antamansid commented on src/ui/src/components/Content/Content.tsx
> +        // console.log(type)
Забытый `console.log`

2024-03-01 08:37 UTC, Antamansid commented on src/ui/src/components/Content/Content.tsx
> +    const onSkillQuestion: ISortQuestion['onSkillQuestion'] = (skill) => {
Не обернуты функции в `useCallback`.
Это осознанно?
Причин этого не делать не вижу.

2024-03-01 08:37 UTC, Antamansid commented on src/ui/src/controllers/GetAnswer.js
> +export default function GetAnswer () {
А это еще актуально?

2024-03-01 18:05 UTC, fenab-bojko commented on src/ui/src/App.tsx
> +  const openModal = useCallback(() => setShowModal(true), [])
?

2024-03-11 17:28 UTC, Antamansid commented on package.json
удали файл и сделай в директории `npm init -y` )))

2024-03-11 17:29 UTC, Antamansid commented on src/ui/src/App.tsx
> +  const openModal = useCallback(() => setShowModal(true), [])
```tsx
const openModal: IContentProps["openModal"] = useCallback(...);
```

2024-03-13 19:13 UTC, Antamansid requested changes

2024-03-13 19:13 UTC, Antamansid commented on src/ui/src/components/Modal/Modal.tsx
> +    const sendQuestion: IModalProps['onSendQuestion'] = useCallback((textQuestion, topic, skill, textAnswer, name) => {
sendQuestion это функция не Modal, а Button

2024-03-13 19:13 UTC, Antamansid commented on src/ui/src/components/QuestionContainer/QuestionsContainer.tsx
> +                        <li key={elem.id} onClick={() => handlerClick(elem.id)}>
Вытащи в отдельный компонент и там напиши функцию onClick

2024-03-13 19:13 UTC, Antamansid commented on src/ui/backend/lib/data.ts
> +export async function fetchAdd () {
Создай папку model в src. Создай там папку answer. Создай там файл api.ts.
Там создай класс AnswersApi и все эти методы туда.

2024-03-21 17:35 UTC, Antamansid requested changes

2024-03-21 17:35 UTC, Antamansid commented on src/ui/src/App.tsx
> +export type TSendQuestion = (question: string, language: string, skill: string, answer: string, name: string) => void;
Это не должно быть тут

2024-03-29 18:30 UTC, Antamansid approved these changes

2024-03-29 18:32 UTC, merged